version: '3.0'
services:


  lipsync:
    image: "franzzle/lipsync-flux-api"
    environment:
      WAV_STORAGE_DIR: /output/lipsyncwavs
      JSON_STORAGE_DIR: /output/lipsyncjsons
      APP_RHUBARB_DIR: /rhubarb/Rhubarb-Lip-Sync-1.13.0-Linux
    ports:
      - "9180:9180"
    volumes:
      - lipsyncwavs:/output/lipsyncwavs

# Names our volumes , TODO add one
volumes:
  lipsyncwavs:
