version: '3.0'
services:


  lipsync:
    image: "franzzle/lipsync-flux-api"
    environment:
      WAV_STORAGE_DIR: /output/lipsyncwavs
      APP_RHUBARB_DIR: /rhubarb/rhubarb-lip-sync-1.10.0-linux
    ports:
      - "9180:9180"
    volumes:
      - lipsyncwavs:/output/lipsyncwavs

# Names our volumes , TODO add one
volumes:
  lipsyncwavs:
